import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Shared/Navbar/page";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html
            theme="light"
            lang="en"
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
            <body className="flex flex-col">
                <header className="sticky top-0 z-40 border-b border-border/60 bg-background/80 backdrop-blur">
                    <Navbar />
                </header>
                {children}
            </body>
        </html>
    );
}
